---
all:
  children:
    juniper:
      hosts:
#        SBERCORE:
#          ansible_connection: ansible.netcommon.network_cli
#          ansible_network_os: junipernetworks.junos.junos
#          ansible_host: ip_address
#          ansible_port: 22
#          ansible_user: user
#          ansible_password: pass

    hiershman:
      hosts:
        acs-A10-14:
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_host: ip_address
          ansible_port: 22
          ansible_user: user
          ansible_password: pass
          
