---
all:
  children:
    juniper:
      hosts:
        Jun_EX_QFX:
          ansible_connection: ansible.netcommon.network_cli
          ansible_network_os: junipernetworks.junos.junos
          ansible_host: ip_address
          ansible_port: 22
          ansible_user: user
          ansible_password: pass
    hiershman:
      hosts:
        BCS:
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_host: ip_address
          ansible_port: 22
          ansible_user: user
          ansible_password: pass
          
